apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:masters
      rolearn: arn:aws:iam::332739227583:role/UdacityFlaskDeployCBKubectlRole
      username: build
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::332739227583:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1WNR9HOBITK0P
      username: system:node:{{EC2PrivateDNSName}}
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2021-09-06T18:56:32Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1253"
  uid: f85b82c1-a4e1-48a3-868d-d1bac44cecba
